name: build-pi-zero

on:
  push:
  workflow_dispatch:

jobs:
  build-pi-zero:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ARMv6 Liquidsoap (Pi Zero W)
        run: |
          docker buildx build \
            --platform linux/arm/v6 \
            -f pi-zero-bookworm.dockerfile \
            -t liquidsoap-pi-zero \
            --output type=tar,dest=build-pi-zero.tar \
            .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-pi-zero-bookworm
          path: build-pi-zero.tar
